### ISSUE TITLE
Compiler disallowing abstract with-er method

### ISSUE THREAD

**Issue by veyndan** [gabrielittner/auto-value-with#29]
I have been trying to figure out the reason for this problem for a while now. By my understanding I should just be able to add the dependency to my `build.gradle` and use the abstract with-er method based on another "attributes" name. However, I keep getting this error:

`@AutoValue classes cannot have abstract methods other than property getters and Builder converters`

Is this an error on my end, or is this a library bug? Thanks for any help in advance, and here's my code for the problematic model class:

@AutoValue
public abstract class Comic {

    public static final String TABLE = "xkcd";

    public static final String NUM = BaseColumns._ID;
    public static final String ALT = "alt";
    public static final String IMG = "img";
    public static final String TITLE = "title";
    public static final String IMG_RATIO = "imgRatio";

    @ColumnName(NUM)
    public abstract int num();
    public abstract String alt();
    public abstract String img();
    public abstract String title();
    public abstract float imgRatio();

    public abstract Comic withImgRatio(float imgRatio);

    public abstract ContentValues toContentValues();

    public static JsonAdapter<Comic> jsonAdapter(Moshi moshi) {
        return new AutoValue_Comic.MoshiJsonAdapter(moshi);
    }

    public static Comic create(Cursor cursor) {
        return AutoValue_Comic.createFromCursor(cursor);
    }

    public static final Func1<Cursor, Comic> MAPPER = Comic::create;

    public String displayNum() {
        return "#" + num();
    }
}

**Comment by gabrielittner** [comment]
Is your compilation failing? The message you have posted is usually a warning by AutoValue which will be fixed in the next AutoValue release.

**Comment by veyndan** [comment]
Yes it is, the AutoValue classes don't seem to be generating when I use the with-er. Is there anyway of getting around this? Or do I just have to wait for the next AutoValue release?

**Comment by gabrielittner** [comment]
No it should work with 1.2. Can you copy and paste the complete gradle
output?

**Comment by veyndan** [comment]
Executing tasks: [:app:incrementalDebugSupportDex]

Configuration on demand is an incubating feature.
Jack is required to support java 8 language features.
Incremental java compilation is an incubating feature.
Jack is required to support java 8 language features.
:app:buildInfoDebugLoader
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72340Library UP-TO-DATE
:app:prepareComAndroidSupportCardviewV72340Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2340Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2340Library UP-TO-DATE
:app:prepareComJakewhartonButterknife801Library UP-TO-DATE
:app:prepareComJakewhartonRxbindingRxbinding040Library UP-TO-DATE
:app:prepareComSquareupSqlbriteSqlbrite063Library UP-TO-DATE
:app:prepareComTrelloRxlifecycle061Library UP-TO-DATE
:app:prepareComTrelloRxlifecycleComponents061Library UP-TO-DATE
:app:prepareIoReactivexRxandroid120Library UP-TO-DATE
:app:prepareDebugDependencies
:app:transformClassesWithExtractJarsForDebug UP-TO-DATE
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/veyndan/AndroidStudioProjects/Hermes/app/src/main/java/com/veyndan/hermes/home/model/Comic.java:32: warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters
    public abstract Comic withImgRatio(float imgRatio);
                          ^
/Users/veyndan/AndroidStudioProjects/Hermes/app/src/main/java/com/veyndan/hermes/home/model/Comic.java:32: warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters
    public abstract Comic withImgRatio(float imgRatio);
                          ^
/Users/veyndan/AndroidStudioProjects/Hermes/app/build/generated/source/apt/debug/com/veyndan/hermes/home/model/AutoValue_Comic.java:13: error: AutoValue_Comic is not abstract and does not override abstract method withImgRatio(float) in Comic
final class AutoValue_Comic extends $AutoValue_Comic {
      ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
2 warnings

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.566 secs

**Comment by gabrielittner** [comment]
It looks like the extension isn't applied. Can you make sure auto-value-with is in the dependency list when running `gradle app:dependencies --configuration=apt`?

**Comment by veyndan** [comment]
Yeah it is showing up, here's the cropped output:

+--- com.gabrielittner.auto.value:auto-value-with:0.1.3
|    +--- com.google.auto.value:auto-value:1.2
|    +--- com.google.auto:auto-common:0.6 (*)
|    +--- com.google.auto.service:auto-service:1.0-rc2 (*)
|    +--- com.gabrielittner.auto.value:auto-value-extension-util:0.1.1
|    |    +--- com.google.auto:auto-common:0.6 (*)
|    |    +--- com.google.auto.service:auto-service:1.0-rc2 (*)
|    |    +--- com.squareup:javapoet:1.6.0 -> 1.7.0
|    |    \--- com.google.auto.value:auto-value:1.2-rc1 -> 1.2
|    \--- com.squareup:javapoet:1.6.0 -> 1.7.0

**Comment by gabrielittner** [comment]
Please try if it does work with `auto-value-with:0.1.4` and `auto-value-cursor:0.5.0`, if not it would be nice if you could create a sample project that reproduces the error (I'm not seeing it).

**Comment by veyndan** [comment]
Thanks! Updating the dependencies seems to have fixed the error. Thanks again for all the quick responses and helping me with this problem.

**Comment by hamen** [comment]
Hi Gabriel, unfortunately I'm having the same issue. This is my model:

```java
@AutoValue
public abstract class File implements Parcelable {

    public abstract String id();

    public abstract String messageId();

    @Nullable
    public abstract String localUri();

    public abstract String remoteUri();

    public abstract String type();

    public abstract long size();

    public static Builder builder() {
        return new AutoValue_CatapushFile.Builder()
            .id(UUID.randomUUID().toString());
    }
    public abstract CatapushFile withLocalUri(String localUri);

    @AutoValue.Builder
    public abstract static class Builder {

        public abstract Builder id(String id);

        public abstract Builder localUri(@Nullable String localUri);

        public abstract Builder remoteUri(String remoteUri);

        public abstract Builder messageId(String messageId);

        public abstract Builder type(String type);

        public abstract Builder size(long size);

        public abstract CatapushFile build();
    }

    public boolean isImage() {
        final String type = this.type();
        return type.equals(Mimes.PNG) || type.equals(Mimes.JPG);
    }
}
```

If I remove:
```
 public abstract CatapushFile withLocalUri(String localUri);
```
everything is fine, but with the `withLocalUri` line I get:

```
warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters
/Users/hamen/code/[...]/library/app/src/main/java/com/[...]/library/messages/File.java:34: warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters
    public abstract File withLocalUri(String localUri);
                                 ^
:app:compileProductionDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProductionDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.squareup.javapoet.CodeBlock.of(Ljava/lang/String;[Ljava/lang/Object;)Lcom/squareup/javapoet/CodeBlock;
```

I'm using:

```
    provided "com.google.auto.value:auto-value:1.2"
    apt "com.google.auto.value:auto-value:1.2"
    apt 'com.ryanharter.auto.value:auto-value-parcel:0.2.1'
    apt 'com.gabrielittner.auto.value:auto-value-cursor:0.5.0'
    apt 'com.gabrielittner.auto.value:auto-value-with:0.1.4'
```

I have also tried without the `Parcelable` extension but I get the same error message.

Any help? 😕

**Comment by gabrielittner** [comment]
Do you use Dagger 2? If yes it should be fixed by adding javapoet 1.7 as an apt dependency before dagger.

**Comment by hamen** [comment]
Thank you, Gabriel. Adding _JavaPoet_ solved the issue with Dagger2:
```
apt 'com.squareup:javapoet:1.7.0'
compile "com.google.dagger:dagger:${DAGGER_VERSION}"
apt "com.google.dagger:dagger-compiler:${DAGGER_VERSION}"
```
